






































































































































































import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillLinkedin, AiFillGithub , AiFillFacebook} from 'react-icons/ai'
import Image from "next/image";
import deved from "../public/dev-ed-wave.png"
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react';
export default function Home() {
  const [darkMode , setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Potifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
          <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-teal-600'>developedbyhk</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill onClick={()=>{setDarkMode(!darkMode)}} className='cursor-pointer text-xl dark:text-white'/>
                </li>
                <li>
                  <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a>
                </li>
              </ul>
            </nav>
            <div className='text-center p-8'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Hussein Alkattash</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Front end developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>Freelancer providing services from Programming and design beautiful front end. Join me below lets get cracking!</p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillFacebook/>
              <AiFillLinkedin/>
              <AiFillGithub/>
            </div>
            <div className='relative mx-auto mb-8 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} layout="fill" objectFit='cover'/>
            </div>
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-teal-500'>Services I offer</h3>
              <p className='text-md py-2 leading-8 text-gray-800  dark:text-gray-300'>
                Since the beginning of my journey as freelance developer, I have done remote work for
                <span className='text-teal-500'> agencies</span> consulted for  
                <span className='text-teal-500'> startups</span> and collaborated with talanted people to create digital products for both business and consumer use
              </p>
              <p className='text-md leading-8 text-gray-800  dark:text-gray-300'>
                I offer from a wide range of services, including programming and teaching 
              </p>
            </div>
            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={design} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
                <p className='dark:text-gray-300'>Creating elegant designs and front ends for your needs</p>
                <h4 className='py-4 text-teal-600'>Design tools I ues</h4>
                <p className='text-gray-800 py-1 dark:text-gray-200'>HTML</p>
                <p className='text-gray-800 py-1  dark:text-gray-200'>CSS</p>
                <p className='text-gray-800 py-1  dark:text-gray-200'>Bootstrap</p>
                <p className='text-gray-800 py-1  dark:text-gray-200'>Tailwind CSS</p>
                <p className='text-gray-800 py-1  dark:text-gray-200'>Sass</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={consulting} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
                <p className='dark:text-gray-300'>Creating elegant designs and front ends for your needs</p>
                <h4 className='py-4 text-teal-600'>Design tools I ues</h4>
                <p className='text-gray-800 py-1 dark:text-gray-200'>HTML</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Bootstrap</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Tailwind CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Sass</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image src={code} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
                <p className='dark:text-gray-300'>Creating elegant designs and front ends for your needs</p>
                <h4 className='py-4 text-teal-600'>Design tools I ues</h4>
                <p className='text-gray-800 py-1 dark:text-gray-200'>HTML</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Bootstrap</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Tailwind CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-200'>Sass</p>
              </div>
            </div>
            <div>
              <h3 className='text-3xl py-1 dark:text-teal-500'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
                Since the beginning of my journey as freelance developer, I have done remote work for
                <span className='text-teal-500'> agencies</span> consulted for  
                <span className='text-teal-500'> startups</span> and collaborated with talanted people to create digital products for both business and consumer use
              </p>
              <p className='text-md leading-8 text-gray-800 dark:text-gray-300'>
                I offer from a wide range of services, including programming and teaching 
              </p>
              <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
                  <div className='basis-1/3 flex-1'>
                      <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
                  </div>
              </div>
            </div>
          </section>
      </main>
    </div>
  )
}
